#!/usr/bin/env zsh

export PERL5LIB=lib

checks="DING Ulm Hbf
SVV Salzburg Hbf
VOR Wien Hbf
Verbundlinie Graz Hbf
LinzAG Linz Hbf
VGN Nürnberg Hbf
VRR Essen Hbf
VRR2 Essen Hbf
VVS Stuttgart Schwabstraße
VVO Dresden Hbf
VRN Mannheim Hbf
NVBW Stuttgart Hbf (A.-Klett-Pl.)
VMV Schwerin Hbf
KVV Karlsruhe Hbf
TLEM London Waterloo East
VBL Luzern Bf
BSVG Braunschweig Hbf"

echo $checks | while read service name place; do
	echo -n "${service} ... "
	if bin/efa-m -s $service $name $place > /dev/null; then
		echo OK
	fi
done
